---
title: "owner_KarthikcharanSuresh"
author: "Karthikcharan Suresh"
date: "9/11/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Name

My name is Karthikcharan Suresh

# My Major

What I tell most people about my major is that I'm learning about data science, which has statistics, programing, high level maths, and machine learning.

# Organizational Strategies

I organize my day very well and the top three are 

## I play my day in advanvce

I have a planner where I write all the work that needs to done the next day.


## Every night before going to sleep

I read my goal everynight, short, medium and long just to keep me reminded where im running towards

## I have a personal journal

I write down the things that I did in a day, and try to analyze the wrongs I did and how to correct it.

#exerciseQuestion_1
X = c(47,34,33,65,37,NA,43,NA,11,NA,23,NA)
count = 0
for (var in X)
  if (is.na(var))
    count = count  + 1
print(count)

#exerciseQuestion_2
age = c(25,30,45,60,12,41)
smoker = c('T','F','T','F','F','F')
weight = c(120,137,0,168,91,142)
weight[3] = 150
example_data = data.frame(age,smoker,weight)

#exerciseQuestion_3
meanNums <- function (x)
  {
  mean(x, na.rm = TRUE)
  }
setDividedbySum <- function (x)
  {
  x / sum(x, na.rm = TRUE)
  }
meanNums(x)
setDividedbySum(x)

#exerciseQuestion_4
both_NA <- function(a,b) {
  count = 0
  for (var in 1:length(a))
    if (is.na(a[var]) && is.na(b[var]))
      count = count  + 1
    print(count)
}

both_NA(X,X)
